# Fields 75 - 107: Student Manually Entered Financial
# Source: 2025-26 FAFSA Specifications Guide, Vol 4A
LAYOUT = {
    "f75": {"label": "Received EITC", "pos": (697, 697), "len": 1, "type": "num"},
    "f76": {"label": "Received Federal Housing Assistance", "pos": (698, 698), "len": 1, "type": "num"},
    "f77": {"label": "Received Free/Reduced Price Lunch", "pos": (699, 699), "len": 1, "type": "num"},
    "f78": {"label": "Received Medicaid", "pos": (700, 700), "len": 1, "type": "num"},
    "f79": {"label": "Received Refundable Credit for 36B Health Plan", "pos": (701, 701), "len": 1, "type": "num"},
    "f80": {"label": "Received SNAP", "pos": (702, 702), "len": 1, "type": "num"},
    "f81": {"label": "Received Supplemental Security Income", "pos": (703, 703), "len": 1, "type": "num"},
    "f82": {"label": "Received TANF", "pos": (704, 704), "len": 1, "type": "num"},
    "f83": {"label": "Received WIC", "pos": (705, 705), "len": 1, "type": "num"},
    "f84": {"label": "Federal Benefits: None of the Above", "pos": (706, 706), "len": 1, "type": "num"},
    "f85": {"label": "Filed 1040 or 1040NR", "pos": (707, 707), "len": 1, "type": "num"},
    "f86": {"label": "Filed Non-U.S. Tax Return", "pos": (708, 708), "len": 1, "type": "num"},
    "f87": {"label": "Filed Joint Return with Current Spouse", "pos": (709, 709), "len": 1, "type": "num"},
    "f88": {"label": "Tax Return Filing Status", "pos": (710, 710), "len": 1, "type": "num"},
    "f89": {"label": "Income Earned from Work", "pos": (711, 721), "len": 11, "type": "num"},
    "f90": {"label": "Tax Exempt Interest Income", "pos": (722, 732), "len": 11, "type": "num"},
    "f91": {"label": "Untaxed Portions of IRA Distributions", "pos": (733, 743), "len": 11, "type": "num"},
    "f92": {"label": "IRA Rollover", "pos": (744, 754), "len": 11, "type": "num"},
    "f93": {"label": "Untaxed Portions of Pensions", "pos": (755, 765), "len": 11, "type": "num"},
    "f94": {"label": "Pension Rollover", "pos": (766, 776), "len": 11, "type": "num"},
    "f95": {"label": "Adjusted Gross Income", "pos": (777, 786), "len": 10, "type": "num"},
    "f96": {"label": "Income Tax Paid", "pos": (787, 795), "len": 9, "type": "num"},
    "f97": {"label": "Earned Income Tax Credit Received During Tax Year?", "pos": (796, 796), "len": 1, "type": "num"},
    "f98": {"label": "Deductible Payments to IRA, Keogh, Other", "pos": (797, 807), "len": 11, "type": "num"},
    "f99": {"label": "Education Credits", "pos": (808, 816), "len": 9, "type": "num"},
    "f100": {"label": "Filed Schedule A, B, D, E, F, or H?", "pos": (817, 817), "len": 1, "type": "num"},
    "f101": {"label": "Schedule C Amount", "pos": (818, 829), "len": 12, "type": "num"},
    "f102": {"label": "College Grant and Scholarship Aid", "pos": (830, 836), "len": 7, "type": "num"},
    "f103": {"label": "Foreign Earned Income Exclusion", "pos": (837, 846), "len": 10, "type": "num"},
    "f104": {"label": "Child Support Received", "pos": (847, 853), "len": 7, "type": "num"},
    "f105": {"label": "Total of Cash, Savings, and Checking Accounts", "pos": (854, 860), "len": 7, "type": "num"},
    "f106": {"label": "Net Worth of Current Investments", "pos": (861, 867), "len": 7, "type": "num"},
    "f107": {"label": "Net Worth of Businesses and Investment Farms", "pos": (868, 874), "len": 7, "type": "num"}
}